# Generated by Django 5.2.17 on 2026-08-22 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servconecta', '0002_mensagemchat_proposta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=90)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='servconecta.categoria')),
            ],
            options={
                'verbose_name': 'Subcategoria',
                'verbose_name_plural': 'Subcategorias',
                'ordering': ['categoria__nome', 'nome'],
                'unique_together': {('categoria', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='oferta',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ofertas', to='servconecta.subcategoria'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes', to='servconecta.subcategoria'),
        ),
    ]
