# Generated by Django 5.2.17 on 2026-08-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servconecta', '0004_encerramento_notificacao_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='imagem_celular',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='ofertas/'),
        ),
        migrations.AddField(
            model_name='oferta',
            name='imagem_tablet',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='ofertas/'),
        ),
    ]
