[project]
name = "serv-conecta"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "João Barboasa", email = "iotabe@iotabe.adm.br" }
]
requires-python = ">=3.14"
dependencies = [
    "django>=5.0,<6.0",
    "pillow>=10.0",
    "psycopg[binary]>=3.2,<4",
    "whitenoise>=6.7,<7",
]

[project.scripts]
serv-conecta = "serv_conecta:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
